import React from 'react';

const RazorpayPayment = () => {
    const handlePayment = async () => {
        const options = {
            key: 'YOUR_RAZORPAY_KEY', // Enter the Key ID generated from the Dashboard
            amount: 50000, // Amount is in currency subunits. Default currency is INR. Hence, 50000 refers to ₹500
            currency: 'INR',
            name: 'Acme Corp',
            description: 'Test Transaction',
            image: 'https://example.com/your_logo',
            order_id: '', // Replace with the order ID generated by the server
            handler: function (response) {
                alert(response.razorpay_payment_id);
                alert(response.razorpay_order_id);
                alert(response.razorpay_signature);
            },
            prefill: {
                name: 'John Doe',
                email: 'john.doe@example.com',
                contact: '9999999999',
            },
            theme: {
                color: '#F37254',
            }
        };

        const rzp1 = new window.Razorpay(options);
        rzp1.open();
    };

    return (
        <div>
            <button onClick={handlePayment}>Pay with Razorpay</button>
        </div>
    );
};

export default RazorpayPayment;
